### PR TITLE
Append whiteboard as tag, thus allowing filtering by language for bugzilla bugs

### LINKED ISSUE #100: Highlight languages / filter by language
One of the benefits of bugsahoy was that you could filter by language (c++/js/etc). There's lots of people that don't know all languages, so it would help people when finding associated bugs.

codetribute could maybe just list the languages, and add a filter, or just do a filter.

I believe it is generally the mentored bugs that have been annotated in the past (not always the good-first-bugs). There are generally annotated in the whiteboard with one of:

```
[lang=js][lang=xul]
[lang=js,xul]
[lang=js/xul]
```

### PR DESCRIPTION
**Pull request by fiennyangeln**
Add whiteboard as field in graphql, extract the string inside square bracket

Closes #100

### CODE REVIEW

File: src/views/Project/index.jsx [hunk 1]
```diff
@@ -288,7 +288,13 @@ export default class Project extends Component {
           bugzillaData.bugs.edges.map(edge => edge.node).map(bug => ({
             assignee: bug.status === 'ASSIGNED' ? bug.assignedTo.name : '-',
             project: bug.component,
-            tags: bug.keywords || [],
+            tags: [
+              ...(bug.keywords || []),
+              ...(
+                (bug.whiteboard && bug.whiteboard.match(/\[.+?\]/g)) ||
```
[the remark this answers is not in the document]
Comment (fiennyangeln) [reply src/views/Project/index.jsx]: should we display other whiteboard tag / just language (the one that starts with lang=)?

[the remark this answers is not in the document]
Comment (fiennyangeln) [reply src/views/Project/index.jsx]: screen shot 2018-07-16 at 1 41 48 pm
when we display everything from whiteboard, some of the tags will be a duplicated, e.g good-first-bug and good first bug, however it cant be detected since one uses space and the other use -

File: src/views/Project/index.jsx [hunk 2]
```diff
@@ -57,6 +57,30 @@ const tagReposMapping = repositories =>
       ...mappings,
     };
   }, {});
+const extractWhiteboardTags = whiteboard => {
```
Comment (djmitche) [inline src/views/Project/index.jsx]: This kind of function just screams for unit tests, doesn't it?  I don't think there's any setup for that in codetribute, though..

**Comment by helfi92** [comment]
Rebasing your work on master will allow you to simply run `yarn test` for running tests with [Jest](https://jestjs.io/). There are 2 requirements for test files that Neutrino enforces by default:
* Test files must live inside the `test` directory
* Test files must end in either `_test.js`, `.test.js`, `_test.jsx`, or `.test.jsx`.

File: src/utils/extractWhiteboard.js [hunk 3]
```diff
@@ -0,0 +1,30 @@
+const extractWhiteboardTags = whiteboard => {
+  // find occurence like lang=perl,js or lang=perl/js
+  const re = /(\w+)=(\w+)[,|/](\w+)/;
+  // find all element within square bracket starting with lang with as little
+  // string as possible inside
+  const keywords = (whiteboard.match(/\[lang.+?\]/g) || []).reduce(
```
Comment (helfi92) [inline src/utils/extractWhiteboard.js]: Put an equal symbol after `lang`: `/\[lang=.+?\]/g) || []`

File: src/utils/extractWhiteboard.js [hunk 4]
```diff
@@ -0,0 +1,30 @@
...
+    (prev, item) => {
+      // remove the square bracket
```
Comment (helfi92) [inline src/utils/extractWhiteboard.js]: s/bracket/brackets/

File: src/utils/extractWhiteboard.js [hunk 5]
```diff
@@ -0,0 +1,30 @@
+const extractWhiteboardTags = whiteboard => {
+  // find occurence like lang=perl,js or lang=perl/js
+  const re = /(\w+)=(\w+)[,|/](\w+)/;
```
Comment (helfi92) [inline src/utils/extractWhiteboard.js]: I'm thinking we might face whiteboard tag of the form `[lang=js, xul]` (notice the space after the comma). See if it is easy to integrate this edge case. If it's too difficult, then it should be okay.

File: src/utils/extractWhiteboard.js [hunk 6]
```diff
@@ -0,0 +1,30 @@
...
+
+      // if there is no comma or /
+      if (!items) {
+        return [...prev, itemWithoutBracket];
+      }
+
+      // items=["lang=js/xul","lang","js","xul"]
+      // so start looping from 3rd element
+      return [
+        ...prev,
```
Comment (helfi92) [inline src/utils/extractWhiteboard.js]: Rename to `acc` for "accumulator".

File: src/utils/extractWhiteboard.js [hunk 7]
```diff
@@ -0,0 +1,30 @@
...
+        ...items.slice(2).map(element => `${items[1]}=${element}`),
+      ];
+    },
+    []
+  );
+
+  return keywords;
+};
+
```
Comment (helfi92) [inline src/utils/extractWhiteboard.js]: Rename file name to `extractWhiteboardTags.js`.

File: src/utils/extractWhiteboard.js [hunk 8]
```diff
@@ -0,0 +1,30 @@
+const extractWhiteboardTags = whiteboard => {
```
Comment (helfi92) [inline src/utils/extractWhiteboard.js]: You can instead do

```js
export default (whiteboard) => {
 // ...
};
```

After that you can delete ` export default extractWhiteboardTags; `

File: src/utils/extractWhiteboard.js [hunk 9]
```diff
@@ -0,0 +1,30 @@
...
+  // find occurence like lang=perl,js or lang=perl/js
```
Comment (helfi92) [inline src/utils/extractWhiteboard.js]:
```
// Find whiteboard tags of the form:
// [lang=js][lang=xul]
// [lang=js,xul]
// [lang=js/xul]
```

File: src/utils/extractWhiteboard.js (hunk 5 above)
Comment (helfi92) [inline src/utils/extractWhiteboard.js]: Add a condition on top of this line:

```js
if (!whiteboard) {
  return [];
}
```

File: src/views/Project/index.jsx [hunk 10]
```diff
@@ -289,7 +290,11 @@ export default class Project extends Component {
           bugzillaData.bugs.edges.map(edge => edge.node).map(bug => ({
             assignee: bug.status === 'ASSIGNED' ? bug.assignedTo.name : '-',
             project: bug.component,
-            tags: bug.keywords || [],
+            tags: [
+              ...(bug.keywords || []),
+              ...((bug.whiteboard && extractWhiteboardTags(bug.whiteboard)) ||
```
Comment (helfi92) [inline src/views/Project/index.jsx]: If you include a check in `extractWhiteBoardTags` that returns an empty array if `bug.whiteboard` is invalid, then you can do:

```jsx
tags: [
  ...(bug.keywords || []),
  ...(extractWhiteboardTags(bug.whiteboard)),
],

```

File: test/extract_whiteboard_test.js [hunk 11]
```diff
@@ -0,0 +1,24 @@
...
+    const whiteboard = '[lang=js][lang=xul]';
+    const result = extractWhiteboardTags(whiteboard);
+    expect(result).toEqual(['lang=js', 'lang=xul']);
+  });
+  it('should ignore other whiteboard tag besides language', () => {
+    const whiteboard = '[good-first-bug]';
+    const result = extractWhiteboardTags(whiteboard);
+    expect(result).toEqual([]);
+  });
+  it('should handle comma tag', () => {
```
Comment (helfi92) [inline test/extract_whiteboard_test.js]: Have a test case for each of the following whiteboard tags:

* [lang=js][lang=xul]
* [lang=js][lang=xul][good-first-bug]
* [lang=js,xul]
* [lang=js/xul]
* [lang=js, xul] (if not too hard to integrate)

_Example:_

```js
it('should extract languages from [lang=js][lang=xul][good-first-bug]', () => {
 // ...
})
```

File: test/extract_whiteboard_test.js [hunk 12]
```diff
@@ -0,0 +1,24 @@
...
+    const whiteboard = '[lang=js,xul]';
+    const result = extractWhiteboardTags(whiteboard);
```
Comment (helfi92) [inline test/extract_whiteboard_test.js]: `whiteboard` is not used multiple times, so you can just inline it.

```js
const result = extractWhiteboardTags('[lang=js,xul]');
```

Perform this change for the other test cases as well.

File: src/utils/extractWhiteboardTags.js [hunk 13]
```diff
@@ -1,23 +1,30 @@
-const extractWhiteboardTags = whiteboard => {
-  // find occurence like lang=perl,js or lang=perl/js
-  const re = /(\w+)=(\w+)[,|/](\w+)/;
+export default whiteboard => {
+  // Find whiteboard tags of the form:
+  // [lang=js][lang=xul]
+  // [lang=js,xul]
+  // [lang=js/xul]
```
Comment (helfi92) [inline src/utils/extractWhiteboardTags.js]: Put the comment on top of the exported function:

```js
// <put-comment-here>
export default whiteboard => {
  // ...
};
```

File: test/extract_whiteboard_test.js [hunk 14]
```diff
@@ -0,0 +1,24 @@
...
+  });
+  it('should extract languages from [lang=js,xul]', () => {
+    const result = extractWhiteboardTags('[lang=js,xul]');
+    expect(result).toEqual(['lang=js', 'lang=xul']);
+  });
+  it('should extract languages from [lang=js/xul]', () => {
+    const result = extractWhiteboardTags('[lang=js/xul]');
+    expect(result).toEqual(['lang=js', 'lang=xul']);
+  });
+  it('should extract languages from [lang=js, xul]', () => {
```
Comment (helfi92) [inline test/extract_whiteboard_test.js]: Do the test pass with this new addition? We should probably have travis run the tests on each commit.

Comment (fiennyangeln) [reply test/extract_whiteboard_test.js]: yes it does

Comment (helfi92) [reply test/extract_whiteboard_test.js]: Feel free to add it :)

File: .travis.yml [hunk 15]
```diff
@@ -14,3 +14,4 @@ install:
 script:
 - yarn lint
 - yarn build
+- yarn test
```
Comment (helfi92) [inline .travis.yml]: Add newline.
