### PR TITLE
Fix error in the console

### LINKED ISSUE #76: Errors in the console when running the app locally
Running `codetribute` locally I get errors in the console. Let's make the console happy :)

In many of the material-ui components, the API exposes a `component` prop giving you the ability to change its DOM element.

screen shot 2018-07-04 at 10 10 22 am

### PR DESCRIPTION
**Pull request by fiennyangeln**
Use span in the typography component and use withRouter instead of
NavLink to navigate between pages

Fix #76

### CODE REVIEW

File: src/components/ProjectCard/index.jsx [hunk 1]
```diff
@@ -49,30 +50,49 @@ export default class ProjectCard extends Component {
...
+
   render() {
     const {
       classes,
-      project: { name, summary, fileName },
+      project: { name, summary },
     } = this.props;
 
     return (
-      <NavLink className={classes.navlink} to={`/projects/${fileName}`}>
```
Comment (helfi92) [inline src/components/ProjectCard/index.jsx]: Let's use `Link` instead of `NavLink`.

```jsx
import { Link } from 'react-router-dom';`
```

File: src/components/ProjectCard/index.jsx [hunk 2]
```diff
@@ -49,30 +50,49 @@ export default class ProjectCard extends Component {
...
+      const code = event.charCode || event.keyCode;
+
+      if (code !== 32 && code !== 13) {
+        return;
+      }
+    }
+
+    this.props.history.push(`/projects/${fileName}`);
+  };
+
```
Comment (helfi92) [inline src/components/ProjectCard/index.jsx]: I would stay away from this if we can handle it using the `Link` component.

File: src/components/ProjectCard/index.jsx (hunk 1 above)
Comment (fiennyangeln) [reply src/components/ProjectCard/index.jsx]: @helfi92 but aren't both will render similarly as <a>?

File: src/components/ProjectCard/index.jsx (hunk 2 above)
Comment (fiennyangeln) [reply src/components/ProjectCard/index.jsx]: ok! will try it

File: src/components/ProjectCard/index.jsx (hunk 1 above)
Comment (helfi92) [reply src/components/ProjectCard/index.jsx]: `NavLink` is meant to be used for navigation. When the URL matches the `to` prop, it will attach an`active` class to the component which we don't want to do here. `NavLink` uses `Link` internally.

Comment (helfi92) [reply src/components/ProjectCard/index.jsx]: I see. In that case, you can do `component="object"`. When an element is wrapped with `<object>` the DOM will consider this as an external resource and will be treated without looking at the parent element. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/object.

```jsx
<Typography component="object" ...>
   ...
</Typography>
```

Comment (fiennyangeln) [reply src/components/ProjectCard/index.jsx]: WOW how did you find such simple solution ✨
