### PR TITLE
Display unassigned bugs by default

### LINKED ISSUE #38: Display unassigned bugs by default

### PR DESCRIPTION
**Pull request by fiennyangeln**
Add switch to which is defaulted to false (not display assigned bugs)

Fix #38

### CODE REVIEW

**Comment by fiennyangeln** [comment]
@helfi92 I initially want to use it but i think it might be hard to find since the table has longer length than the screen sometimes. can we put it on the left?

**Comment by helfi92** [comment]
If you look at the example from the link I provided, you will see the table has a longer length (requires the user to scroll horizontally to see all of the columns) but the filter icon is always visible since it sits on top of the Table component.

**Comment by fiennyangeln** [comment]
@helfi92 oh okok thanks!

File: src/components/DataTable/index.jsx [hunk 1]
```diff
@@ -1,19 +1,29 @@
...
 import TableBody from '@material-ui/core/TableBody';
 import TableCell from '@material-ui/core/TableCell';
 import TableHead from '@material-ui/core/TableHead';
 import TableRow from '@material-ui/core/TableRow';
 import TableSortLabel from '@material-ui/core/TableSortLabel';
-import { arrayOf, func, string, oneOf, object } from 'prop-types';
+import Typography from '@material-ui/core/Typography';
+import IconButton from '@material-ui/core/IconButton';
+import FilterVariantIcon from 'mdi-react/FilterVariantIcon';
+import Toolbar from '@material-ui/core/Toolbar';
```
Comment (helfi92) [inline src/components/DataTable/index.jsx]: Move `Toolbar` on top of `FilterVariantIcon` so that `material-ui` packages are grouped together.

File: src/components/DataTable/index.jsx [hunk 2]
```diff
@@ -67,40 +92,56 @@ class DataTable extends Component {
...
-              ))}
-            </TableRow>
-          </TableHead>
+      <Fragment>
+        {title && (
+          <Toolbar>
+            <Typography variant="title" className={classes.title}>
+              {title}
+            </Typography>
+            <div className={classes.spacer} />
```
Comment (helfi92) [inline src/components/DataTable/index.jsx]: Let's not use empty `div`s.

File: src/components/DataTable/index.jsx [hunk 3]
```diff
@@ -59,6 +78,12 @@ class DataTable extends Component {
     }
   };
 
+  handleFilterClick = () => {
+    if (this.props.onFilterClick) {
+      this.props.onFilterClick();
```
Comment (helfi92) [inline src/components/DataTable/index.jsx]: Clicking on the filter icon should open a menu item with "Unassigned" as a menu item. Clicking on "Unassigned" should show bugs/issues that are unassigned.

Comment (fiennyangeln) [reply src/components/DataTable/index.jsx]: Right now it opens the filter form which has a switch with the word "Also display assigned bugs"  since the default is to display the unassigned bugs , do you mean using drop down button with Unassigned as the default selected?

Comment (helfi92) [reply src/components/DataTable/index.jsx]: Not necessarily. It should be okay having "Unassigned" not selected by default but let the user select it if they can't find unassigned bugs/issues.

File: src/components/DataTable/index.jsx [hunk 4]
```diff
@@ -46,11 +53,20 @@ class DataTable extends Component {
...
+    /**
+     * A function to execute when the filter icon is clicked.
+     */
+    onFilterClick: func,
   };
 
   static defaultProps = {
     sortByHeader: null,
     sortDirection: 'desc',
+    filters: undefined,
```
Comment (helfi92) [inline src/components/DataTable/index.jsx]: `filters: null,`

File: src/components/FilterForm/index.jsx [hunk 5]
```diff
@@ -0,0 +1,96 @@
...
+export default class FilterMenu extends Component {
+  state = {
+    anchorEl: null,
+  };
+
+  getSelectedAssignee() {
+    const { assignee } = this.getQuery();
+
+    return assigneeList.indexOf(assignee) > -1 ? assignee : ASSIGNEE.UNASSIGNED;
+  }
```
Comment (helfi92) [inline src/components/FilterForm/index.jsx]: A component should not be getting data from the URL rather it should be getting them from props. We should define props for this component.

File: src/components/FilterForm/index.jsx [hunk 6]
```diff
@@ -0,0 +1,96 @@
...
+
+  getQuery() {
+    const { location } = this.props;
+    const query = parse(location.search.slice(1));
+
+    return query;
+  }
```
Comment (helfi92) [inline src/components/FilterForm/index.jsx]: Remove `getQuery` and use `props` instead.

File: src/components/FilterForm/index.jsx [hunk 7]
```diff
@@ -0,0 +1,96 @@
...
+
+  handleClickListItem = event => {
```
Comment (helfi92) [inline src/components/FilterForm/index.jsx]: Use the format `handle${subject}Click`. In our case maybe something like `handleAssigneeClick`.

File: src/components/FilterForm/index.jsx [hunk 8]
```diff
@@ -0,0 +1,96 @@
...
+
+  handleMenuItemClick = (event, assignee) => {
+    this.setState({ anchorEl: null });
+    this.props.history.push({
+      search: `?${stringify({
+        ...this.getQuery(),
+        assignee,
+      })}`,
+    });
+  };
```
Comment (helfi92) [inline src/components/FilterForm/index.jsx]: If we are going to make this file a component then we shouldn't be making URL changes in the component. It should be handled by the parent view.

File: src/components/FilterForm/index.jsx [hunk 9]
```diff
@@ -0,0 +1,96 @@
...
+        <Menu
+          id="lock-menu"
+          anchorEl={anchorEl}
+          open={Boolean(anchorEl)}
+          onClose={this.handleClose}>
+          {assigneeList.map(assignee => (
+            <MenuItem
+              key={assignee}
+              selected={assignee === selectedAssignee}
+              onClick={event => this.handleMenuItemClick(event, assignee)}>
```
Comment (helfi92) [inline src/components/FilterForm/index.jsx]: I'm not sure having two `onClick` (one on `ListItem` and one here) is necessary. Have a look at `TextField` [menu example](https://material-ui.com/demos/text-fields/#textfield) where they show how you can do everything using one onChange handler.

File: src/components/FilterForm/index.jsx [hunk 10]
```diff
@@ -0,0 +1,96 @@
...
+const assigneeList = Object.values(ASSIGNEE);
+
+@withRouter
+@withStyles(theme => ({
+  root: {
+    margin: `0px ${3 * theme.spacing.unit}px`,
+    maxWidth: 360,
+  },
+}))
+export default class FilterMenu extends Component {
```
Comment (helfi92) [inline src/components/FilterForm/index.jsx]: The directory name is `FilterForm` but the component name is `FilterMenu`. They should be the same.

File: src/components/TasksTable/index.jsx [hunk 11]
```diff
@@ -36,6 +38,10 @@ const sorted = pipe(
   },
 }))
 export default class TasksTable extends Component {
+  state = {
+    displayFilter: false,
```
Comment (helfi92) [inline src/components/TasksTable/index.jsx]: Rename to `showFilterContent`.

File: src/utils/constants.js [hunk 12]
```diff
@@ -0,0 +1,7 @@
+/* eslint-disable */
+
+export const ASSIGNEE = {
+  ANY: 'Any',
+  UNASSIGNED: 'Unassigned',
+  ASSIGNED: 'Assigned',
+};
```
Comment (helfi92) [inline src/utils/constants.js]: 👍

File: src/components/FilterForm/index.jsx [hunk 13]
```diff
@@ -0,0 +1,60 @@
...
+
+    return assigneeList.indexOf(assignee) > -1 ? assignee : ASSIGNEE.UNASSIGNED;
+  }
+
+  handleFilterItemClick = event => {
+    this.props.onFilterItemClick({ assignee: event.target.value });
+  };
+
+  render() {
+    const selectedAssignee = this.getSelectedAssignee();
```
Comment (helfi92) [inline src/components/FilterForm/index.jsx]: No need to have a method for that. Use it inside the `render` method.

```jsx
const assignment = assigneeList.includes(assignee) ? assignee : ASSIGNEE.UNASSIGNED;
```

File: src/components/FilterForm/index.jsx [hunk 14]
```diff
@@ -0,0 +1,60 @@
...
+    const { classes } = this.props;
+
+    return (
+      <div className={classes.root}>
+        <TextField
+          select
+          label="Assignee"
+          value={selectedAssignee}
+          onChange={this.handleFilterItemClick}>
```
Comment (helfi92) [inline src/components/FilterForm/index.jsx]: Rename to `handleFilterChange`.

File: src/components/FilterForm/index.jsx [hunk 15]
```diff
@@ -0,0 +1,60 @@
...
+          {assigneeList.map(assignee => (
+            <MenuItem key={assignee} value={assignee}>
+              {assignee}
+            </MenuItem>
+          ))}
+        </TextField>
+      </div>
+    );
+  }
+}
```
Comment (helfi92) [inline src/components/FilterForm/index.jsx]: This component simply renders a `TextField`. We don't need a filter component for that. We can just use `TextField` directly inside `TasksTable`.

File: src/components/TasksTable/index.jsx [hunk 16]
```diff
@@ -33,6 +35,10 @@ const sorted = pipe(
   },
 }))
 export default class TasksTable extends Component {
+  state = {
+    showFilterContent: false,
```
Comment (helfi92) [inline src/components/TasksTable/index.jsx]: Will assignee be the only filter option we show? If this is the case, then maybe when a user clicks on the filter icon, we display the `<TextField select ... />` directly. If there's only one filter planned (at least for the MVP) then we don't need to have the dedicated filter content area.

To show which filter is selected, I can see us putting a check (✓) icon beside the menu item name.

Comment (helfi92) [reply src/components/TasksTable/index.jsx]: In that case, maybe having the dedicated filter content area makes sense.

File: src/components/FilterForm/index.jsx (hunk 15 above)
Comment (fiennyangeln) [reply src/components/FilterForm/index.jsx]: if there is two `TextField`, wdyt? Or should i save it for later?

Comment (helfi92) [reply src/components/FilterForm/index.jsx]: For now let's remove this component and just inline it in `TasksTable`.

File: src/components/TasksTable/index.jsx [hunk 17]
```diff
@@ -70,11 +86,28 @@ export default class TasksTable extends Component {
...
     };
   }
 
+  setQuery = query => {
+    this.props.history.push({
+      search: `?${stringify(query)}`,
+    });
+  };
+
+  handleFilterClick = () => {
```
Comment (helfi92) [inline src/components/TasksTable/index.jsx]: Let's rename this function to `handleFilterToggle`.

File: src/components/FilterForm/index.jsx [hunk 18]
```diff
@@ -0,0 +1,66 @@
+import { Component } from 'react';
+import { withRouter } from 'react-router-dom';
+import MenuItem from '@material-ui/core/MenuItem';
+import TextField from '@material-ui/core/TextField';
+import { withStyles } from '@material-ui/core/styles';
+import CheckIcon from 'mdi-react/CheckIcon';
```
Comment (helfi92) [inline src/components/FilterForm/index.jsx]: Now that we will keep the filter area content, we won't need the check icon. Let's bring it back to how it was previously.

File: src/components/FilterForm/index.jsx [hunk 19]
```diff
@@ -0,0 +1,66 @@
...
+import { func, string } from 'prop-types';
+import { ASSIGNEE } from '../../utils/constants';
+
+const assigneeList = Object.values(ASSIGNEE);
```
Comment (helfi92) [inline src/components/FilterForm/index.jsx]: Rename to `assignments`.

File: src/components/DataTable/index.jsx [hunk 20]
```diff
@@ -74,16 +94,23 @@ class DataTable extends Component {
...
       items,
       title,
+      filters,
     } = this.props;
     const colSpan = (headers && headers.length) || 0;
 
     return (
       <Fragment>
         {title && (
           <Toolbar>
```
Comment (helfi92) [inline src/components/DataTable/index.jsx]:
```jsx
toolbar: {
  justifyContent: 'space-between',
},


// ...
<Toolbar className={classes.toolbar}>
```

File: src/components/DataTable/index.jsx [hunk 21]
```diff
@@ -74,16 +94,23 @@ class DataTable extends Component {
...
-            <Typography variant="title">{title}</Typography>
+            <Typography variant="title" className={classes.title}>
```
Comment (helfi92) [inline src/components/DataTable/index.jsx]: Remove `className={classes.title}`.

File: src/components/TasksTable/index.jsx [hunk 22]
```diff
@@ -31,8 +35,18 @@ const sorted = pipe(
   tags: {
     whiteSpace: 'nowrap',
   },
+  dropdown: {
+    minWidth: 200,
+  },
+  filter: {
+    padding: `0px ${3 * theme.spacing.unit}px`,
```
Comment (helfi92) [inline src/components/TasksTable/index.jsx]: On smaller screens this will not align with "Bugs & Issues" because the padding changes with screen size. To fix this you can do:

```jsx
filter: {
  ...theme.mixins.gutters(),
},
```

File: src/components/DataTable/index.jsx [hunk 23]
```diff
@@ -74,16 +94,21 @@ class DataTable extends Component {
...
     const colSpan = (headers && headers.length) || 0;
 
     return (
       <Fragment>
         {title && (
-          <Toolbar>
+          <Toolbar className={classes.toolbar}>
             <Typography variant="title">{title}</Typography>
+            <IconButton onClick={this.handleFilterClick}>
+              <FilterVariantIcon onClick={this.handleFilterClick} />
```
Comment (helfi92) [inline src/components/DataTable/index.jsx]: Remove the `onClick` from `FilterVariantIcon` since we already have it on `IconButton`.
