### PR TITLE
Fetch bugzilla bugs with language query without project

### LINKED ISSUE #155: Create UI for search bug / issue by language without selecting project
User should be able to:
-  navigate to and from homepage
-  pick the language
- show table

### PR DESCRIPTION
**Pull request by fiennyangeln**
This is branched from #157. 

- Map the bugzilla whiteboard query name and standard name (in utils.js)
- Query from bugzilla using the whiteboard tag
- Display the query result and the possible error

Now that we don't do more fetchMore should I add loading state?

Closes #155

### CODE REVIEW

**Comment by helfi92** [comment]
Do you think it makes sense for this PR to be merged with https://github.com/mozilla-frontend-infra/codetribute/pull/157?

**Comment by fiennyangeln** [comment]
I separate it to make it easy to review, this one for the fetching and other for the UI, but ok then, will rebase the other to here

**Comment by fiennyangeln** [comment]
@helfi92 i rebased the #157 to this branch

**Comment by helfi92** [comment]
Please close either https://github.com/mozilla-frontend-infra/codetribute/pull/157 or https://github.com/mozilla-frontend-infra/codetribute/pull/163, and let me know which one you want me to look at.

**Comment by fiennyangeln** [comment]
Ok! closed #157, please look at this one.

**Comment by fiennyangeln** [comment]
Ok done 👍

File: src/utils/constants.js [hunk 1]
```diff
@@ -14,3 +14,16 @@ export const ASSIGNEE = {
   ASSIGNED: 'Assigned',
 };
 export const ALL_PROJECTS = 'All';
+export const BUGZILLA_LANGUAGE_MAPPING = {
```
Comment (helfi92) [inline src/utils/constants.js]: Rename to `BUGZILLA_LANGUAGES`.

File: src/views/Languages/bugs.graphql [hunk 2]
```diff
@@ -0,0 +1,18 @@
...
+        lastChanged
+        id
+        keywords
+        summary
+        status
+        whiteboard
+      }
+    }
+  }
+}
```
Comment (helfi92) [inline src/views/Languages/bugs.graphql]: This seems to be a duplicate of `src/views/Project/bugs.graphql`. Move this file to `src/views` and import it from there for both views.

File: src/views/Languages/comments.graphql [hunk 3]
```diff
@@ -0,0 +1,5 @@
+query comments($id: Int!){
+    comments(id: $id){
+        text
+    }
+}
```
Comment (helfi92) [inline src/views/Languages/comments.graphql]: This seems to be a duplicate of `src/views/Project/comments.graphql`. Move this file to `src/views` and import it from there for both views.

File: src/views/Languages/index.jsx [hunk 4]
```diff
@@ -0,0 +1,265 @@
...
+  BUGZILLA_ORDER,
+  BUGZILLA_PAGE_NUMBER,
+  BUGZILLA_PAGE_SIZE,
+  BUGZILLA_STATUSES,
+  GOOD_FIRST_BUG,
+  BUGZILLA_LANGUAGE_MAPPING,
+} from '../../utils/constants';
+import extractWhiteboardTags from '../../utils/extractWhiteboardTags';
+
+const DRAWER_WIDTH = 300;
```
Comment (helfi92) [inline src/views/Languages/index.jsx]: Have this value be defined in `theme.js`. Example from tc-web: https://github.com/taskcluster/taskcluster-web/blob/df3c01703bdfc5d295c1f40988a2dbed59afbf31/src/theme.js#L86.

File: src/views/Languages/index.jsx [hunk 5]
```diff
@@ -0,0 +1,265 @@
...
+            container
+            className={classes.title}
+            alignItems="center"
+            spacing={8}>
+            <Hidden mdUp>
+              <Grid item>
+                <IconButton
+                  className={classes.button}
+                  size="large"
+                  onClick={this.handleDrawerToggle}>
```
Comment (helfi92) [inline src/views/Languages/index.jsx]: The drawer should be open by default on bigger screen sizes but closed on smaller ones.

_Example: taskcluster-web Desktop view_

screen shot 2018-07-31 at 8 40 02 am

_Example: taskcluster-web mobile (smaller screen size) view_

screen shot 2018-07-31 at 8 40 45 am

File: src/views/Languages/index.jsx [hunk 6]
```diff
@@ -0,0 +1,265 @@
...
+            {drawer}
+          </Drawer>
+        </Hidden>
+        <div className={classes.container}>
+          {error && <ErrorPanel error={error} />}
+          {bugzillaData &&
+            bugzillaData.error && <ErrorPanel error={bugzillaData.error} />}
+          {bugzillaData &&
+            bugzillaData.loading && <Spinner className={classes.spinner} />}
+          <TasksTable items={bugs} onBugInfoClick={this.handleBugInfoClick} />
```
Comment (helfi92) [inline src/views/Languages/index.jsx]: When the spinner is showing, we should not show `TasksTable`.

File: src/views/Languages/index.jsx (hunk 5 above)
Comment (helfi92) [reply src/views/Languages/index.jsx]: The screenshots are from `http://localhost:5080/provisioners`. But yes, the drawer behavior should be on Codetribute's home screen.

File: src/components/Sidebar/index.jsx [hunk 7]
```diff
@@ -0,0 +1,75 @@
...
+
+    return (
+      <List disablePadding>
+        {items.map(item => (
+          <ListItem
+            className={classNames({
+              [classes.active]: activeItem === item.text,
+            })}
+            button
+            onClick={this.handleItemClick}
```
Comment (eliperelman) [inline src/components/Sidebar/index.jsx]: This event handler is redundant, you can pass `this.props.onItemClick` directly.

File: src/components/Sidebar/index.jsx [hunk 8]
```diff
@@ -0,0 +1,72 @@
...
+            <ListItemIcon>{item.icon || <WebIcon />}</ListItemIcon>
+            <ListItemText disableTypography className={classes.text}>
+              {item.text}
+            </ListItemText>
+          </ListItem>
+        ))}
+      </List>
+    );
+  }
+}
```
Comment (helfi92) [inline src/components/Sidebar/index.jsx]: The drawer seems to have a right blue border. Let's remove that.

screen shot 2018-08-01 at 9 16 44 am

Comment (helfi92) [reply src/components/Sidebar/index.jsx]: When you hover over a project on the far left, the spacing between the scaled project and the drawer should be the same as the distance between neighboring projects.

screen shot 2018-08-01 at 9 19 19 am

Comment (helfi92) [inline src/components/Sidebar/index.jsx]: What do you think about switching the background colors?

**Note:** Since this will require making a modification to the theme file as well as making sure it works with the homepage, I suggest we do that in a different PR.

## Before

screen shot 2018-08-01 at 9 22 52 am

## After

screen shot 2018-08-01 at 9 22 41 am

File: src/views/Languages/index.jsx [hunk 9]
```diff
@@ -0,0 +1,269 @@
...
+          {bugzillaData &&
+            bugzillaData.loading && <Spinner className={classes.spinner} />}
+          {(!bugzillaData || !bugzillaData.loading) && (
+            <TasksTable items={bugs} onBugInfoClick={this.handleBugInfoClick} />
+          )}
+        </div>
+      </div>
+    );
+  }
+}
```
Comment (helfi92) [inline src/views/Languages/index.jsx]: The only difference between this view and the project view is the GraphQL query right? To ensure we don't have a lot of duplication, I suggest we use  the same file for `/languages` and `/project`. You can then construct the query based on the URL location.

Comment (fiennyangeln) [reply src/views/Languages/index.jsx]: i think another different is that we dont have the Sidebar for the `/project` and project information in the `/languages`. But yeah except to the query variables, most of them are similar

Comment (fiennyangeln) [reply src/views/Languages/index.jsx]: and the css is different too because of the sidebar, wdyt? @helfi92

Comment (helfi92) [reply src/views/Languages/index.jsx]: Ah, in that case we can probably keep the current setup.

Comment (fiennyangeln) [reply src/views/Languages/index.jsx]: Ok then 👍

File: src/components/Sidebar/index.jsx [hunk 10]
```diff
@@ -0,0 +1,72 @@
...
+      CSS: <LanguageCss3Icon />,
+    };
+    const items = Object.keys(BUGZILLA_LANGUAGES).map(text => ({
+      text,
+      icon: icons[text],
+    }));
+
+    return (
+      <List disablePadding>
+        {items.map(item => (
```
Comment (helfi92) [inline src/components/Sidebar/index.jsx]: `Object.keys(BUGZILLA_LANGUAGES).map`

File: src/components/Sidebar/index.jsx [hunk 11]
```diff
@@ -0,0 +1,72 @@
...
+            className={classNames({
+              [classes.active]: activeItem === item.text,
+            })}
+            button
+            onClick={this.props.onItemClick}
+            id={item.text}
+            key={item.text}
+            component={Link}
+            to={`/languages/${item.text}`}>
+            <ListItemIcon>{item.icon || <WebIcon />}</ListItemIcon>
```
Comment (helfi92) [inline src/components/Sidebar/index.jsx]:
```jsx
<ListItemIcon>{icons[language] || <WebIcon />}</ListItemIcon>
```

File: src/components/Sidebar/index.jsx [hunk 12]
```diff
@@ -0,0 +1,72 @@
...
+      Swift: <LanguageSwiftIcon />,
+      C: <LanguageCIcon />,
+      'C++': <LanguageCppIcon />,
+      'C#': <LanguageCsharpIcon />,
+      CSS: <LanguageCss3Icon />,
+    };
+    const items = Object.keys(BUGZILLA_LANGUAGES).map(text => ({
+      text,
+      icon: icons[text],
+    }));
```
Comment (helfi92) [inline src/components/Sidebar/index.jsx]: Remove `items`.

File: src/views/Languages/index.jsx [hunk 13]
```diff
@@ -0,0 +1,297 @@
...
+import extractWhiteboardTags from '../../utils/extractWhiteboardTags';
+
+const bugzillaSearchOptions = {
+  statuses: Object.values(BUGZILLA_STATUSES),
+  order: BUGZILLA_ORDER,
+};
+const bugzillaPagingOptions = {
+  page: BUGZILLA_PAGE_NUMBER,
+  pageSize: BUGZILLA_PAGE_SIZE,
+};
```
Comment (helfi92) [inline src/views/Languages/index.jsx]: Since we're using this object in multiple places, we can probably have this in `constant.js` as

```js
BUGZILLA_PAGING_OPTIONS = {
  // ...
}
```

File: src/views/Languages/index.jsx [hunk 14]
```diff
@@ -0,0 +1,297 @@
...
+            <TasksTable
+              items={[...goodFirstBugs, ...mentoredBugs]}
+              onBugInfoClick={this.handleBugInfoClick}
+            />
+          )}
+        </div>
+      </div>
+    );
+  }
+}
```
Comment (helfi92) [inline src/views/Languages/index.jsx]: Instead of duplicating the Drawer, could we create a Dashboard component (somewhat similar to tc-web) that takes care of rendering `AppBar` and `Drawer`? We can have this component expose a `withSkills` prop defaulting to `false`. When `withSkills` is set to `true`, the drawer can be displayed. As a result, we won't need to duplicate all of the drawer and Appbar CSS.

File: src/views/Languages/index.jsx [hunk 15]
```diff
@@ -0,0 +1,297 @@
...
+            id: bug.id,
+            url: `https://bugzilla.mozilla.org/show_bug.cgi?id=${bug.id}`,
+          })),
+          'summary'
+        )) ||
+      [];
+
+    return (
+      <div className={classes.root}>
+        <AppBar position="fixed" className={classes.header}>
```
Comment (helfi92) [inline src/views/Languages/index.jsx]: Similar to the project view, we want a back arrow button that will navigate the user back to the main view.

File: src/components/Dashboard/index.jsx [hunk 16]
```diff
@@ -0,0 +1,218 @@
+import { Component, Fragment } from 'react';
```
Comment (helfi92) [inline src/components/Dashboard/index.jsx]: Instead of:

screen shot 2018-08-02 at 9 01 00 am

I was thinking something like:

screen shot 2018-08-02 at 9 00 41 am

What do you think?

File: src/components/Dashboard/index.jsx [hunk 17]
```diff
@@ -0,0 +1,218 @@
...
+import { Link } from 'react-router-dom';
```
Comment (helfi92) [inline src/components/Dashboard/index.jsx]: * The Github icon should be on the far right.
* The sandwich menu should be on the left since that's where the drawer will be coming from.

File: src/components/Dashboard/index.jsx (hunk 16 above)
Comment (helfi92) [reply src/components/Dashboard/index.jsx]: I'm open to a different design if you don't like the one I suggested.

Comment (fiennyangeln) [reply src/components/Dashboard/index.jsx]: as for the padding-top in the skill drawer, i add it to make the 'Skills' word appear in the `/languages/:language` actually

Comment (helfi92) [reply src/components/Dashboard/index.jsx]: I don't think it's necessary to have the skills drawer when viewing the language view. We can remove it.

File: src/views/Projects/index.jsx [hunk 18]
```diff
@@ -70,50 +117,30 @@ export default class Projects extends Component {
...
-        <main className={classes.container}>
-          <Grid container spacing={24} className={classes.grid}>
-            {Object.values(filteredProjects)
-              .sort((a, b) => {
-                const firstElement = a.name;
-                const secondElement = b.name;
+      <Dashboard
+        classes={{
+          container: classes.container,
+          header: classes.header,
```
Comment (helfi92) [inline src/views/Projects/index.jsx]: Why does `header` take a function?

File: src/views/Languages/index.jsx [hunk 19]
```diff
@@ -0,0 +1,142 @@
...
+            lastUpdated: bug.lastChanged,
+            id: bug.id,
+            url: `https://bugzilla.mozilla.org/show_bug.cgi?id=${bug.id}`,
+          })),
+          'summary'
+        )) ||
+      [];
+
+    return (
+      <Dashboard activeItem={language} withSidebar>
```
Comment (helfi92) [inline src/views/Languages/index.jsx]: No need provide the `activeItem` prop. I believe you can infer this from the last parameter of the URL.

File: src/components/Sidebar/index.jsx [hunk 20]
```diff
@@ -0,0 +1,68 @@
...
+
+    return (
+      <List disablePadding>
+        {Object.keys(BUGZILLA_LANGUAGES).map(language => (
+          <ListItem
+            className={classNames({
+              [classes.active]: activeItem === language,
+            })}
+            button
+            onClick={this.props.onItemClick}
```
Comment (helfi92) [inline src/components/Sidebar/index.jsx]: `onLanguageClick`

File: src/components/Sidebar/index.jsx [hunk 21]
```diff
@@ -0,0 +1,68 @@
...
+      'C#': <LanguageCsharpIcon />,
+      CSS: <LanguageCss3Icon />,
+    };
+
+    return (
+      <List disablePadding>
+        {Object.keys(BUGZILLA_LANGUAGES).map(language => (
+          <ListItem
+            className={classNames({
+              [classes.active]: activeItem === language,
```
Comment (helfi92) [inline src/components/Sidebar/index.jsx]: Get active state from URL.

File: src/views/Projects/index.jsx (hunk 18 above)
Comment (helfi92) [reply src/views/Projects/index.jsx]: I think you should be able to provide the JSX without putting it in a function.

**Comment by fiennyangeln** [comment]
screen shot 2018-08-03 at 1 56 01 am
is it something like this?

**Comment by helfi92** [comment]
Remove the "<" button and have the "Skills" background be blue.

screen shot 2018-08-02 at 1 23 48 pm
