### PR TITLE
Fix sorting for tag by providing support for array type

### LINKED ISSUE #54: Sorting by tag not working
Clicking on the "Tag" column throws an error in the console: `referenceElement.match is not a function`.

### PR DESCRIPTION
**Pull request by fiennyangeln**
Fix #54

### CODE REVIEW

File: src/components/DataTable/index.jsx [hunk 1]
```diff
@@ -54,7 +54,7 @@ class DataTable extends Component {
   };
 
   handleHeaderClick = ({ target }) => {
-    if (this.props.onHeaderClick) {
+    if (this.props.onHeaderClick && target.id !== 'Tags') {
```
Comment (helfi92) [inline src/components/DataTable/index.jsx]: `DataTable` should not have knowldege of `Tags`. Put this logic in `TasksTable`.

**Comment by helfi92** [comment]
Merge when ready.
